services:
  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-cruz-ml-backend-v2
    image: app-cruz-ml-backend:v2
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ml-model:/app/ml-model
      - app-cruz-ml-db-data-v2:/app/data
    environment:
      - PYTHONPATH=/app:/app/ml-model
      - DATABASE_PATH=/app/data/patients.db
      - TF_CPP_MIN_LOG_LEVEL=2
    networks:
      - app-cruz-ml-network-v2
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s

  # Frontend React
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app-cruz-ml-frontend-v2
    image: app-cruz-ml-frontend:v2
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - app-cruz-ml-node-modules-v2:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-cruz-ml-network-v2
    restart: unless-stopped

networks:
  app-cruz-ml-network-v2:
    name: app-cruz-ml-network-v2
    driver: bridge

volumes:
  app-cruz-ml-node-modules-v2:
    name: app-cruz-ml-node-modules-v2
  app-cruz-ml-db-data-v2:
    name: app-cruz-ml-db-data-v2
